name: open_git
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.0+4
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #http
  dio: ^2.1.7
  #http
  connectivity: ^0.3.2
  json_annotation: ^2.4.0
  shared_preferences: ^0.4.3
  markdown: ^2.0.3
  flutter_markdown: ^0.2.0
  flutter_redux: ^0.5.3
  fluro: ^1.5.0
  package_info: ^0.4.0+4
  qr_flutter: ^2.1.0+55
  permission_handler: ^3.1.0
  # 数据库
  sqflite: ^1.1.6
  # 文件管理
  path_provider: ^0.5.0+1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.1
  json_serializable: ^3.0.0
  #####本地库
  install_apk_plugin:
    path: ./flutter_common_lib/install_apk_plugin
  flutter_base_ui:
    path: ./flutter_common_lib/flutter_base_ui
  flutter_common_util:
    path: ./flutter_common_lib/flutter_common_util


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - assets/data/language_colors.json

    - assets/images/ic_launcher.png
    - assets/images/ic_branch.png
    - assets/images/ic_default_head.png
    - assets/images/1f44d.png
    - assets/images/1f44e.png
    - assets/images/1f389.png
    - assets/images/1f440.png
    - assets/images/1f604.png
    - assets/images/1f615.png
    - assets/images/1f680.png
    - assets/images/2764.png
    - assets/images/ic_like.png
    - assets/images/ic_comment.png
    - assets/images/ic_star.png
    - assets/images/ic_issue.png
    - assets/images/bg_guide_home.png
    - assets/images/bg_guide_repos_detail.png
    - assets/images/bg_guide_issue_detail.png
    - assets/images/bg_guide_theme.png
    - assets/images/bg_splash_ad.png
